version: '3'
services:

  mssql:
    container_name: senzing-mssql
    environment:
#     See https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
      ACCEPT_EULA: ${ACCEPT_EULA:-Y}
      MSSQL_PID: ${MSSQL_PID:-Developer}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-Passw0rd}
    image: mcr.microsoft.com/mssql/server:${SENZING_DOCKER_IMAGE_VERSION_MSSQL_SERVER:-latest}
    networks:
      - senzing
    ports:
      - 1433:1433
    restart: always
    user: "0"
    volumes:
      - ${MSSQL_DIR:-/var/opt/mssql}:/var/opt/mssql

  adminer:
    container_name: senzing-adminer
    environment:
      ADMINER_DEFAULT_SERVER: senzing-mssql
    image: senzing/adminer:${SENZING_DOCKER_IMAGE_VERSION_ADMINER:-latest}
    networks:
      - senzing
    ports:
      - 9177:8080
    restart: always

  mssql-create-db:
    command:
      - /opt/mssql-tools/bin/sqlcmd
      - -P
      - ${MSSQL_SA_PASSWORD:-Passw0rd}
      - -Q
      - "CREATE DATABASE G2"
      - -S
      - ${MSSQL_HOST:-senzing-mssql},${MSSQL_PORT:-1433}
      - -U
      - sa
    container_name: senzing-mssql-create-database
    depends_on:
      - mssql
    image: mcr.microsoft.com/mssql-tools:${SENZING_DOCKER_IMAGE_VERSION_MSSQL_TOOLS:-latest}
    networks:
      - senzing
    restart: on-failure

  init-mssql:
    container_name: senzing-init-mysql
    depends_on:
      - mysql
    environment:
      LC_CTYPE: en_US.utf8
#     See https://github.com/Senzing/init-postgresql#configuration
      SENZING_DATABASE_URL: "mssql://${MSSQL_USERNAME:-g2}:${MSSQL_PASSWORD:-g2}@${MSSQL_HOST:-senzing-mssql}:${MSSQL_PORT:-1433}/${MSSQL_DATABASE:-G2}"
#     SENZING_ENGINE_CONFIGURATION_JSON: >-
#       {
#         "PIPELINE": {
#           "CONFIGPATH": "/etc/opt/senzing",
#           "LICENSESTRINGBASE64": "${SENZING_LICENSE_BASE64_ENCODED}",
#           "RESOURCEPATH": "/opt/senzing/g2/resources",
#           "SUPPORTPATH": "/opt/senzing/data"
#         },
#         "SQL": {
#           "BACKEND": "SQL",
#           "CONNECTION": "mssql://${MYSQL_USERNAME:-g2}:${MYSQL_PASSWORD:-g2}@${MYSQL_HOST:-senzing-mysql}:${MYSQL_PORT:-3306}/?schema=${MYSQL_DATABASE:-G2}"
#         }
#       }
#     SENZING_INPUT_SQL_URL: "file:///opt/senzing/g2/resources/schema/g2core-schema-mysql-create.sql"
      SENZING_SUBCOMMAND: mandatory
    image: senzing/init-mysql:${SENZING_DOCKER_IMAGE_VERSION_INIT_MYSQL:-latest}
    networks:
      - senzing
    read_only: true
    restart: on-failure

networks:
  senzing:
    name: ${SENZING_DOCKER_NETWORK:-senzing-network}
